module.exports = {
  env: {
    CLOUDINARY_CLOUDNAME: process.env.CLOUDINARY_CLOUDNAME,
    CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET
  }
}